export const NODE_ENV = 'NODE_ENV';
export const APP_ENV = 'APP_ENV';

export const PORT = 'PORT';

export const COOKIE_SECRET = 'COOKIE_SECRET';
export const JWT_SECRET = 'JWT_SECRET';

export const COGNITO_USER_POOL_ID = 'COGNITO_USER_POOL_ID';
export const COGNITO_CLIENT_ID = 'COGNITO_CLIENT_ID';
export const COGNITO_CALLBACK_URL = 'COGNITO_CALLBACK_URL';
export const AWS_REGION = 'AWS_REGION';

export const IPSTACK_KEY = 'IPSTACK_KEY';
export const MAXMIND_ACCOUNT_ID = 'MAXMIND_ACCOUNT_ID';
export const MAXMIND_KEY = 'MAXMIND_KEY';

export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';

export const MONGODB_URI = 'MONGODB_URI';

export const FRONTEND_URL = 'FRONTEND_URL';

export const WEBAUTHN_RP_ID = 'WEBAUTHN_RP_ID';
export const WEBAUTHN_RP_NAME = 'WEBAUTHN_RP_NAME';
export const WEBAUTHN_ORIGIN = 'WEBAUTHN_ORIGIN';
export const WEBAUTHN_AUTHENTICATOR_ATTACHMENT =
  'WEBAUTHN_AUTHENTICATOR_ATTACHMENT';
